### ISSUE TITLE
Add support for comments in PhpCode extractor

### ISSUE THREAD

**Issue by mlocati** [oscarotero/Gettext#100]
When using xgettext to extract translatable strings from PHP files we have the option to extract comments (the [`-add-comments`](https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/xgettext-Invocation.html#Operation-mode) option):

For instance, let's say we have this `test.php` file

```php
<?php

echo __(
	/* i18n: %1$s is the partial number, %2$s is the total number. Example: 2 of 3 */
	'%1$s of %2$s',
	$count,
	$total
);

```

If you run this command:
```sh
xgettext --add-comments=i18n --keyword=__:1 --add-location test.php
```

Here's the output:
```po
#. i18n: %1$s is the partial number, %2$s is the total number. Example: 2 of 3
#: test.php:5
#, php-format
msgid "%1$s of %2$s"
msgstr ""
```

What about adding support to extract such comments?

**Comment by oscarotero** [comment]
I'm agree. I knew there were comments in gettext but I didn't know that they had to be placed there.
One question: comments with `//` are allowed too?

**Comment by mlocati** [comment]
From

```php
<?php

echo __(
    /* i18n: Test comment 1 */
	 'test 1'
);

echo __(
    // i18n: Test comment 2
	 'test 2'
);

echo __(
    # i18n: Test comment 3
	 'test 3'
);
```

`xgettext` extracts this

```po
#. i18n: Test comment 1
#: test.php:5
msgid "test 1"
msgstr ""

#. i18n: Test comment 2
#: test.php:10
msgid "test 2"
msgstr ""

#. i18n: Test comment 3
#: test.php:15
msgid "test 3"
msgstr ""
```

**Comment by oscarotero** [comment]
nice!

**Comment by oscarotero** [comment]
I guess this can be closed

**Comment by mlocati** [comment]
> I guess this can be closed

:+1:
