### ISSUE TITLE
Extractors\PhpCode does not extract d__() and other domain-related gettext functions

### ISSUE THREAD

**Issue by marcandrews** [oscarotero/Gettext#108]
```Extractors\PhpCode``` does not appear to be able to extract ```d__()``` and other domain-related ```gettext``` functions.

**Comment by oscarotero** [comment]
Yes, you're right. This is something that I have in the roadmap but I couldn't find any time yet to implement.
I will add this to 3.6 version

**Comment by marcandrews** [comment]
Thanks!

**Comment by marcandrews** [comment]
First off, thanks for the update.

Am I doing this right? I wish to load two domains and then use `Extractors\PhpCode` to extract code from domain-related `gettext` function

```
require_once 'CldrToGettext/src/autoloader.php';
require_once 'Gettext/src/autoloader.php';

use Gettext\GettextTranslator;

$t = new GettextTranslator();
$t->setLanguage($lang);
$t->loadDomain('common', 'path/to/common/domain/Locale');
$t->loadDomain('local', 'path/to/local/domain/Locale', false);

$t->register();

$extraction = Gettext\Extractors\PhpCode::fromFile('path/file.php');
```

When I run `Extractors\PhpCode`, `__()`, `__e()` get extracted, but `d__('local', 'original')` or `d__e('local', 'original')` are still missed. 

Seems like the class is failing [here](https://github.com/oscarotero/Gettext/commit/ffb2f2d88ecaad8d4cdb1d9496338639a66d0ffb#diff-c39a8ad8478657b8b63da0ab3efb8ee0R79). Does `Extractors\PhpCode` not support multiple domains?

I even tried loading just one domain and it still does not work. Is there something else I'm missing?

**Comment by marcandrews** [comment]
Yes, if I comment out `&& $domain === $translations->getDomain()` from [here](https://github.com/oscarotero/Gettext/commit/ffb2f2d88ecaad8d4cdb1d9496338639a66d0ffb#diff-c39a8ad8478657b8b63da0ab3efb8ee0R79), it works. Is there a reason you're checking the domain?

**Comment by oscarotero** [comment]
The `Translations` instance contains only one domain. So you have to define which domain you want to get before extract the code. Example:

```php
use Gettext\Translations;

//Create a empty Translations
$translations = new Translations();

//Set the domain
$translations->setDomain('local');

//Extract the entries of this domain:
$translations->addFromPhpCodeFile('path/file.php');

//Save the file
$translations->toMoFile('path/to/local/domain/Locale/en/LC_MESSAGES/messages.mo');

```

**Comment by oscarotero** [comment]
The reason of `$domain === $translations->getDomain()` is to do not mix entries of different domains.

**Comment by marcandrews** [comment]
Thanks! Got it working!
