### ISSUE TITLE
Empty translation prepends generated PO

### ISSUE THREAD

**Issue by marcandrews** [oscarotero/Gettext#109]
When generating PO files, this [line](https://github.com/oscarotero/Gettext/blob/master/src/Generators/Po.php#L14) always prepends an empty translation:
```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
...
```

Because of this, if I have an empty text in my `gettext` or `__` function, e.g. `__('')`, it will be replaced by _Project-Id-Version: Report-Msgid-Bugs-To: ..._ and the entire header.

What is the purpose of this empty translation? Can it be removed?

**Comment by mlocati** [comment]
No, it's the [header of the gettext file](https://www.gnu.org/software/gettext/manual/gettext.html#Header-Entry) and it contains some required information (like plural definition, text encoding, language, ...).

**Comment by oscarotero** [comment]
Maybe the gettext functions should return an empty string if the msgid is empty too?

**Comment by marcandrews** [comment]
I understand that that is the header, but no where in the [specification](https://www.gnu.org/software/gettext/manual/gettext.html#PO-Files) does it say that PO files must begin with:
```
msgid ""
msgstr ""
```
... and this is what `Generators\Po` is added to the beginning of the generated PO.

**Comment by oscarotero** [comment]
At the end of this section say:

> An empty untranslated-string is reserved to contain the header entry with the meta information (see Header Entry). This header entry should be the first entry of the file. The empty untranslated-string is reserved for this purpose and must not be used anywhere else.

**Comment by marcandrews** [comment]
Nice find. I think I know what the problem is: `Generators\Po` should prepend POs not with:
```
msgid ""
msgstr ""
```
... but with `msgid ""` **only**.

For example, if the PO starts like this:
```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2016-05-06T10:42:44-04:00\n"
"PO-Revision-Date: 2016-05-06T10:42:44-04:00\n"
"Language: \n"
```
... what this says is that empty strings, e.g. `__('')`, should be replaced with _Project-Id-Version: Report-Msgid-Bugs-To: Last-Translator:
Language-Team: MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: 8bit POT-Creation-Date: 2016-05-06T10:42:44-04:00 PO-Revision-Date: 2016-05-06T10:42:44-04:00 Language:_

Perhaps the PO should actually look like this:
```
msgid ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2016-05-06T10:42:44-04:00\n"
"PO-Revision-Date: 2016-05-06T10:42:44-04:00\n"
"Language: \n"
```
... without `msgstr ""`

The specification mentions an _empty **un**translated-string_, but says nothing about an _empty translated-string_ (i.e. `msgstr ""`).

**Comment by marcandrews** [comment]
I don't know ... all the examples I find on have the `msgstr ""` though.

**Comment by marcandrews** [comment]
If the PO generation is correct, I think having the  `Translator` function skip empty strings is another possible solution.

**Comment by mlocati** [comment]
Think of msgid as a record identifier. With your approach, how can a program find the PO header? The doc says that the header *should* be the first entry, not that it *must* be the first, so there only way to define a header is by using a fixed value for msgid (and the empty string is the safest one, I mean the one that should not clash with any application).

Furthermore, gettext files are so widely used that changing its structure is not feasible in practice... It'd require to rewrite a few thousands of programs in a few millions of instances...

**Comment by mlocati** [comment]
> If the PO generation is correct, I think having the Translator function skip empty strings is another possible solution.

In that case how could we retrieve the header value?

**Comment by mlocati** [comment]
> I don't know ... all the examples I find on have the msgstr "" though.

You mean that all the .po files start like this?
```gettext
msgid ""
msgstr ""
"Something else"
"Something else"
"Something else"

```

If this is the case, please note that the value of msgstr is not an emty string, since its value is built by concatenating the initial empty string with all the non-empty strings that follow...

**Comment by marcandrews** [comment]
No, all the examples of PO files with headers I see begin with:
```
msgid ""
msgstr ""
"Project-Id-Version: \n"
...
```
... i.e. with `msgstr ""`



But I am beginning to understand now that this is actually a _feature_ to retrieve the header information at some end point with `_('')` or `gettext('')`.

Still, I don't know why this particular class needs this feature when your [cldr-to-gettext-plural-rules](https://github.com/mlocati/cldr-to-gettext-plural-rules) provides a far more elegant solution to getting language CLDR data.

**Comment by oscarotero** [comment]
The headers not only provide CLDR data, but also the translator name, the revision date, revision bugs address, etc.

**Comment by marcandrews** [comment]
Does your class allow you to set these header variables?

**Comment by oscarotero** [comment]
Yes. Here an example: https://github.com/oscarotero/Gettext#translations

**Comment by marcandrews** [comment]
Awesome! Thanks again.
