### ISSUE TITLE
Autocomplete for magic methods

### ISSUE THREAD

**Issue by sourcerer-mike** [oscarotero/Gettext#111]
Hello,

you might like to add this in the Gettext\Translations class for autocomplete:

    * @method toMoFile(string $fileName)

(and others). Works well in phpStorm.

Cheers,

Mike

**Comment by oscarotero** [comment]
That's good idea. I've added these phpdocs. Do you know how to define static methods? This allows to define also the magic factories like `Translations::fromPoFile()`

**Comment by sourcerer-mike** [comment]
Sorry for the late reply. Within phpStorm it is:

    * @method static foo(int $x)
