### ISSUE TITLE
MERGE_REFERENCES should remove "old" references

### ISSUE THREAD

**Issue by sourcerer-mike** [oscarotero/Gettext#113]
When merging

    $a->mergeWith($b, MERGE_REFERENCES);

Then B should overwrite the references of A.

Or as the references of A might not be up-to-date anymore there could be an additional option like `OVERWRITE_*` for each merge option (where it makes sense).

**Comment by oscarotero** [comment]
I preffer `MERGE_OVERRIDE_REFERENCES` because sometimes you want the references of both. For example, you have a translations instance with the php templates entries and other with the javascript files entries and want to merge them.

**Comment by oscarotero** [comment]
I'm working on new more intuitive constants to configure the merge. You can see the docs here: https://github.com/oscarotero/Gettext#merge-translations

Now, some of the mergeable elements have constants like `*_MINES` and `*_THEIRS`, so, for example, to configure the references you can use `Translation::MERGE_REFERENCES_MINES` (to use only the references from `$a`, `Translation::MERGE_REFERENCES_THEIRS` (to use only the references from `$b`) and none (to merge both references).

**Comment by sourcerer-mike** [comment]
I like this solution very much! Mine / Our and theirs is known from `git` and speaks for itself. Good choice! I really like your decisions and think that you are a good developer.

**Comment by oscarotero** [comment]
As you can see, the api changed a bit since that comment (created the Merge class, use of OURS instead MINE) but the main idea is this.
Hapy you like it.
