### ISSUE TITLE
Allow constants as translation domain

### ISSUE THREAD

**Issue by sourcerer-mike** [oscarotero/Gettext#116]
Hello. Congratulations to the Platinum Medal!

Here I am again with some nasty bug. Imagine this code:

```
<?php echo __( 'Something', TEXTDOMAIN_CONSTANT ); ?>
```

Your PhpFunctionsScanner does not recognize the second argument.
It just calls "stopArgument" on src/Utils/PhpFunctionsScanner.php:100

I would suggest this:

- Scan for the closing brackets to really stop arguments.
- If the argument is not T_CONSTANT_ENCAPSED_STRING but exists as a constant, then this is your text domain / real argument value.

So other developers need to introduce such constants before parsing code. This would be a workaround in your scanner after the T_STRING case:

```
case T_STRING:
	                //add an argument to the current function
	                if (defined($value[1]) && constant($value[1])) {
		                $bufferFunctions[0]->addArgumentChunk((string) constant($value[1]));
		                break;
	                }
```

There is more to do but I am not able to handle that at the moment.

Edit: Double checked. That's all for this issue.

**Comment by oscarotero** [comment]
That's good idea. Thanks for the suggestion, I'll implement this as soon as I have some time available.

**Comment by sourcerer-mike** [comment]
I looked at this problem again and tried it. It is very hard for me.
Did you worked on this recently or know how to solve it?

**Comment by oscarotero** [comment]
I didn't work on this yet. My idea, instead evaluate the constants on extracting, was provide a list of key => values to the extractor to make the replacement. For example:

```php
$translations = Translations::fromPhpCodeFile('file.php', [
    'constants' => [
        'TEXT_DOMAIN' => 'foo',
        'OTHER_TEXT_DOMAIN' => 'bar'
    ]
]);
```
This allows to extract the same constant with different values.
I don't think callables or regular variables should be covered, only constants (at least in this first version).

**Comment by oscarotero** [comment]
Well, I've made a commit to allow this. Can you test it, please?
You can use constants as arguments in any gettext function, for example:

```php
p__(CONTEXT_NAME, 'Hello world');
dp__(DOMAIN_NAME, CONTEXT_NAME, 'Hello world');
```

And to scan:
```php
$translations = Translations::fromPhpCodeFile('file.php', [
    'constants' => [
        'CONTEXT_NAME' => 'foo',
        'DOMAIN_NAME' => 'bar'
    ]
]);
```
