### ISSUE TITLE
Feature request: Merge::UPDATE

### ISSUE THREAD

**Issue by lxg** [oscarotero/Gettext#117]
I would propose a feature where `$translations1` imports existing translations from `$translations2`, but doesn’t add new messages which are not present in `$translations1`.

For example, if `$translations1` contains

    {
         "dog" : "Hund",
         "cat" : ""
    }

and `$translations2` contains

    {
         "cat" : "Katze",
         "mouse" : "Maus"
    }

we would have `$translations1->mergeWith($translations2, Merge::UPDATE)` which would only import the translation for `cat` and ignore `mouse`.

**Comment by oscarotero** [comment]
In theory this could be done not adding the flag `Merge::ADD`. For example:

```php
$translation1->mergeWith($translation2, 0);

//or substracting the ADD option from defaults:
$options = Merge::DEFAULTS & Merge::ADD;
$translation1->mergeWith($translation2, $options);
```
Can you confirm if this works for you?

**Comment by mlocati** [comment]
Maybe it's

```php
$options = Merge::DEFAULTS & ~Merge::ADD;
```

**Comment by lxg** [comment]
`$translation1->mergeWith($translation2, 0);` does indeed work. Thanks and sorry for bothering!
