### ISSUE TITLE
Generators/Generator.php ignores $options

### ISSUE THREAD

**Issue by lxg** [oscarotero/Gettext#118]
In version 4.0.1, the generator does not use the passed `$options` array when calling `toString`:

https://github.com/oscarotero/Gettext/blob/master/src/Generators/Generator.php#L14

Obviously, this line should read

    $content = static::toString($translations, $options);

**Comment by lxg** [comment]
https://github.com/oscarotero/Gettext/pull/120

**Comment by oscarotero** [comment]
Good catch! Thank you
