### ISSUE TITLE
4.0.1 plural forms bug

### ISSUE THREAD

**Issue by lxg** [oscarotero/Gettext#119]
When I create a file with the following content:

    <?php ngettext("dog", "dogs", 2);

And I try to extract the string to a .po file like this:

        $catalog = Translations::fromPhpCodeFile("test.php");
        $catalog->setLanguage("de_DE");
        $catalog->toPoFile("test.po");

The resulting file has the following content:

    msgid ""
    msgstr ""
    # [ omitting irrelevant headers ]
    "Language: de_DE\n"
    "Plural-Forms: nplurals=2; plural=n != 1;\n"

    #: test.php:1
    msgid "dog"
    msgid_plural "dogs"
    msgstr[0] ""

I am pretty sure there should be a `msgstr[1] ""` line at the end. Or am I missing something?

**Comment by oscarotero** [comment]
I've commited a fix for this. Can you test it, please?

**Comment by lxg** [comment]
Thanks for the quick fix! I confirm this working for locales with 2 or more plural forms. Tested with `de_DE` and `ru_RU`.
