### ISSUE TITLE
JS extractor chokes on IIFEs

### ISSUE THREAD

**Issue by lxg** [oscarotero/Gettext#122]
Considering the following test code:

    (function(){
        var foo = ["string1", "string2", "string3"];
    })();

This is something the JS parser should ignore. Instead it somehow tries to interpret the array members as function arguments, which causes an exception in vendor/gettext/gettext/src/Utils/FunctionsScanner.php in line 29 “Notice: Undefined offset: 1”.

What helps is to check if the function definition is complete before adding it to the list. For example, one could replace lines [129-131 of Utils/JsFunctionsScanner.php](https://github.com/oscarotero/Gettext/blob/master/src/Utils/JsFunctionsScanner.php#L129-L131) with something like

    if (!empty($bufferFunctions)) {
        $function = array_shift($bufferFunctions);

        if (isset($function[0]) && isset($function[1]) && isset($function[2]))
            $functions[] = $function;
    }

Though this doesn’t solve the underlying problem with the parser.

**Comment by oscarotero** [comment]
Ok, I think its fixed. The problem was that `$this->upStatus()` must be called on close the function, in order to back to the previous status. You can see it here: https://github.com/oscarotero/Gettext/blob/master/src/Utils/JsFunctionsScanner.php#L133
Thanks for the useful feedback.

**Comment by lxg** [comment]
Yes, this seems to catch it. Running the parser on my relatively large JS code base works flawlessly and seems to catch all translations. Thanks again for the great support! :)
