### ISSUE TITLE
Generate a single .po file from different php files

### ISSUE THREAD

**Issue by reardestani** [oscarotero/Gettext#128]
Hi,

How to generate a single .po file for a project like WordPress theme?

I know I can loop through all php files by RecursiveDirectoryIterator or other technics but does this package offer a method to add all the translation strings in one file?

**Comment by oscarotero** [comment]
If you mean to have filesystem tools to scan directories and return files, no, it's out of the scope of this library to provide this. But you can use an array of files to generate a single Translations instance:

```php
use Gettext\Translations;

//Using an array
$files = glob('*.php');
$translations = Translations::fromPhpCodeFile($files);

//Or an interator
$translations = new Translations();
foreach ($directoryIterator as $file) {
    $translations->addFromPhpCodeFile($file);
}

//And then, export all translations in a single .po file
$translations->toPoFile('locales/en.po');
```

I have also a [Robo plugin](https://github.com/oscarotero/GettextRobo) to ease this task. And there's other [cli tools made by other people](https://packagist.org/packages/gettext/gettext/dependents)

**Comment by reardestani** [comment]
Thanks a lot. It's woking. But it does not load the strings from _e() and others. It only loads from __() function.

Is there any way to load from all common functions?

__;_e;_n:1,2;_x:1,2c;_ex:1,2c;_nx:4c,1,2;esc_attr__;esc_attr_e;esc_attr_x:1,2c;esc_html__;esc_html_e;esc_html_x:1,2c;_n_noop:1,2;_nx_noop:3c,1,2;__ngettext_noop:1,2\n"

Thanks in advance.

**Comment by oscarotero** [comment]
You can configure the functions (name => equivalency). If you're using v4.x:

```php
$translations = Translations::fromPhpCodeFile($file, [
    'functions' => [
        'e' => 'gettext',
        'translate_plural' => 'ngettext',
        //etc
    ]
]);
```

In v3.x:

```php
Gettext\Extractors\PhpCode::$functions = [
        'e' => '__',
        'translate_plural' => 'n__',
        //etc
];
$translations = Translations::fromPhpCodeFile($file);
```

**Comment by reardestani** [comment]
Great, how can I find list of all **functions (name => equivalency)**. I know some of them but not all of them.

**Comment by oscarotero** [comment]
You can see the PhpCode extractor class: https://github.com/oscarotero/Gettext/blob/master/src/Extractors/PhpCode.php
