### ISSUE TITLE
.pot file

### ISSUE THREAD

**Issue by reardestani** [oscarotero/Gettext#129]
Hi,

Is there any way to generate a .pot file.

**Comment by oscarotero** [comment]
There's no a Pot extractor/generator. But you can use the Po generator, because the format is the same.

**Comment by devnix** [comment]
I've successfully implemented a PHP scanner that seeks in our whole application and generates a .pot file, the only difference is the extension and that there are no translated strings.

I was wondering if there is a way of updating the generated PO files from the root POT file. I know there is a merging functionality for that.

I'm already using it for a special case, but I feel that the library would not work the same way does poedit when updating a PO from a POT file: the application I am maintaining is some kind of legacy code and the base strings are in spanish. I coded a little cache looking the current loaded language (italian for example) and the wanted base language (english). If a .mo file was not already up to date, I will merge the english translations into the italian ones, to fall back to english if possible.
