### ISSUE TITLE
Custom comments format for extractors

### ISSUE THREAD

**Issue by delmicio** [oscarotero/Gettext#130]
Helo, I'm using v3.
Is there a way to get customs comments formats as xgettext?
`--add-comments=TRANSLATORS: --add-comments=TRANSLATOR: --add-comments=translators: --add-comments=translator:`

this way `addFromPhpCodeFile` only get comments like
`// TRANSLATORS: main menu`
OR
`/* translators: footer copyright */`

**Comment by oscarotero** [comment]
The phpCode extractor [has an option to do that](https://github.com/oscarotero/Gettext/blob/3.x/src/Extractors/PhpCode.php#L45). Example:

```php
Gettext\Extractors\PhpCode::$extractComments = 'translators';
```

**Comment by delmicio** [comment]
@oscarotero nice! 
Is it possible to add multiple strings? may be as an array?
```PHP
Gettext\Extractors\PhpCode::$extractComments = array('translator','translators','TRANSLATOR','TRANSLATORS');
```

_Utils/PhpFunctionScanner.php:153_
```PHP
if (
    $value !== '' 
    && (
        $this->extractComments === '' 
        || (
            !is_array($this->extractComments) 
            && strpos($value, $this->extractComments) === 0
        )
        || (
            is_array($this->extractComments) 
            && in_array($value, $this->extractComments)
        )
    )
) {
    $result = $value;
}
```

**Comment by oscarotero** [comment]
It's not possible right now. Want to work in a pull request?

**Comment by delmicio** [comment]
@oscarotero  PRs sent
