### ISSUE TITLE
What happened to __e?

### ISSUE THREAD

**Issue by Koriit** [oscarotero/Gettext#135]
What happened to __e global functions? It seems like they were removed in v4.0(see 627b53c41cc6). Was there a reason for it? If so, then why examples in README.MD weren't updated?

**Comment by oscarotero** [comment]
The `__e()` function has been removed in the v4.0. The shortcut of `echo __()`, makes sense in php 5.3, but v4.0 removed the support for php 5.3 and in php 5.4 you can simply do `<?= __('string') ?>`, that it's shorter and faster.
And about the README, you're right, I have to fix it. Thanks for letting me know.

**Comment by Koriit** [comment]
Ok, that makes sense. Thanks for the answer. :)
