### ISSUE TITLE
Named placeholders

### ISSUE THREAD

**Issue by rlanvin** [oscarotero/Gettext#138]
I am migrating a big project away from PHP's native gettext and I'd like to use this lib. However we are using named placeholders and it doesn't look like it's possible here. Is there any plan to support named placeholders instead of `sprintf`/`vsprintf` tokens?

For example:

`__('Hello %name%', ['%name%' => $name]);`

Instead of:

`__('Hello %s', $name);`

If not, would you accept a PR to disable including `translator_functions.php` in `BaseTranslator::register`? This way we can use our own `__()` methods which uses `strtr` instead of `vsprintf`. I'm thinking a simple bool argument (default true, to keep backward compatibility) would do the trick, and allow me to manually include my own translator functions after calling `register`.

**Comment by oscarotero** [comment]
Named placeholders have been a recurrent request. The problem with this is there's no a standard syntax for the variables. Some people use `Hello {{name}}`, others `Hello %name%` and php has not a built-in function to handle this, so performance is affected.
Your solution of a bool argument is good.

**Comment by rlanvin** [comment]
> php has not a built-in function to handle this

I don't understand, what's wrong with `strtr` (or `str_replace` if you fancy) and/or what does your lib need to care about the placeholder syntax used? The user can use whatever placeholder format they want. They can even mix multiple format in the same string for that matter. With a  `__()` using `strtr` you can do:

```php
__('Hello {{first_name}} %last_name%', [
    '{{first_name}}' => 'John',
    '%last_name%' => 'Doe'
]);
```

**Comment by oscarotero** [comment]
I always thought this as a standardized way to insert placeholders and using `strtr` in a more free way never had come to my mind. But maybe it's a good solution that can make happy to everybody.

Currently, these functions accept different arguments or an array with all arguments:
https://github.com/oscarotero/Gettext/blob/master/src/translator_functions.php#L56

for example, both following lines are equivalent:

```php
__('Hello %s %s', 'John', 'Doe');
__('Hello %s %s', ['John', 'Doe']);
```

But I suspect nobody is using arrays (it's not documented in the readme) so we could change these methods to use one or other way depending if the argument is an array or not. Example:

```php
__('Hello %s %s', 'John', 'Doe');
__('Hello :first-name :last-name', [':first-name' => 'John', ':last-name' => 'Doe']);
```

Do you want to work in a PR?

**Comment by rlanvin** [comment]
> Do you want to work in a PR?

Yes sure, why not. I was gonna do the `strtr` versions for myself anyway, so I can make a PR. So to recap:

- If the first argument is an array => `strtr` (and other arguments are ignored)
- Else, use `sprintf`

Is that correct? Anything in particular I should take care when working on the PR?

**Comment by oscarotero** [comment]
That's correct. Just try to keep the code style and add any test. Thank you!
