### ISSUE TITLE
Problem with %s and an array of parameters

### ISSUE THREAD

**Issue by Suranex** [oscarotero/Gettext#142]
`__('%s some text %s', ['a', 'b']); ` did not work any more in version 4.3.0. In 4.2.0 it works correct.
I think the bug comes from the changes in https://github.com/oscarotero/Gettext/commit/8cc5a97199ee08063cc8b0347fa184858a5ac5c4. 

PHP: 5.6 
System: Ubuntu with Apache 2.4

**Comment by oscarotero** [comment]
Mmm, yes. This method changed in 4.3.0. If an array is passed, uses `strtr` to provide named placeholders, for example:

```php
__('Hello :name', [':name' => 'World']);
```

Sorry for this breaking change. I thought nobody was using arrays here, it was a undocumented feature. 😞
