### ISSUE TITLE
[Q] How to turn off locations of strings in po file?

### ISSUE THREAD

**Issue by zaigham** [oscarotero/Gettext#143]
How can I achieve the following with `\Gettext\Generators\Po::toFile` ?

```
'--no-location’
Do not write ‘#: filename:line’ lines.
```
I want to remove strings locations from code files in generated PO file.
Thanks.

Ref: https://www.gnu.org/software/gettext/manual/html_node/msgattrib-Invocation.html

**Comment by oscarotero** [comment]
Currently this is not supported, but it's easy to implement.
Meanwhile, you can remote the references before generate the PO file:

```php
foreach ($translations as $translation) {
    $translation->deleteReferences();
}

$translations->toPoFile('locales.po');
```

**Comment by oscarotero** [comment]
I've added this option to po generator (ref: 97d7b7d16f9cc57e89ecdf2cd61dced0796197ca):

```php
$translations->toPoFile('locales.po', ['noLocation' => true]);
```

It will be released in the new version.
