### ISSUE TITLE
Translator function for dngettext()

### ISSUE THREAD

**Issue by ArthurHoaro** [oscarotero/Gettext#146]
Is there any reason for not having a translator function `dn__()` for the `dngettext()` (the plural form with domain and without context) in `translator_functions.php`?

Note that using `dnp__()` with a blank or null context doesn't seem to work with `GettextTranslator`.

**Comment by oscarotero** [comment]
Mmmm, you're right. I don't know why this funcion is missing, but it's good to have it. I did a commit to include it.
Thanks.

**Comment by ArthurHoaro** [comment]
Thanks for your reactivity!
