### ISSUE TITLE
Merge::mergeTranslations() does not properly pass on $options

### ISSUE THREAD

**Issue by melbings** [oscarotero/Gettext#147]
There seems to be a bug in [Merge::mergeTranslations](https://github.com/oscarotero/Gettext/blob/master/src/Merge.php#L146):
```
public static function mergeTranslations(Translations $from, Translations $to, $options = self::DEFAULTS)
    {
        if ($options & self::REMOVE) {
            $filtered = [];

            foreach ($to as $entry) {
                if ($from->find($entry)) {
                    $filtered[$entry->getId()] = $entry;
                }
            }

            $to->exchangeArray($filtered);
        }

        foreach ($from as $entry) {
            if (($existing = $to->find($entry))) {
                $existing->mergeWith($entry); // <--- does not pass on $options
            } elseif ($options & self::ADD) {
                $to[] = $entry;
            }
        }
    }
```

`$options` is not passed on to the single translation `mergeWith()` operations:

```
$existing->mergeWith($entry);
```

Therefore, overwriting translations does not work properly:

```
// Does not actually overwrite translations
$translations->mergeWith($otherTranslations, Merge::ADD | MERGE::HEADERS_ADD | MERGE::HEADERS_OVERRIDE | Merge::TRANSLATION_OVERRIDE);
```

An easy fix would be to pass on `$options` in [Merge.php:162](https://github.com/oscarotero/Gettext/blob/master/src/Merge.php#L162):

```
$existing->mergeWith($entry, $options);
```

**Comment by oscarotero** [comment]
Ok, good catch. Do you mind to create a pull request to fix this? Thank you!

**Comment by melbings** [comment]
Here you go: Pull request https://github.com/oscarotero/Gettext/pull/150

Please note that the PHPUnit tests seem to be broken (and have been before my pull request).

**Comment by oscarotero** [comment]
👍 thanks!
