### ISSUE TITLE
Plurial translation (n__'s function)

### ISSUE THREAD

**Issue by edimitchel** [oscarotero/Gettext#151]
Hello,

I'm using Gettext's registered functions with smarty. When I want to print a singular/plural translation, I'm using `n__` like this :

```
{n__('%d comment', '%d comments', $count)}
```
If `$count` equals 0, it prints `%d comments`, if 1, prints `%d comment`, etc.. 

- **Why the plural purpose is used while the value is not plural ?**
- Why the number isn't printed instead of the marker %d ? However, I make it working to duplicate the `$count` argument like this : 

```
{n__('%d comment', '%d comments', $count, $count)}
```
If `$count` equals 0, it prints `0 comments`, if 1, prints `1 comment`, etc.. 

Perhaps I don't use the function properly ? Can someone explain my problem ?

**Comment by oscarotero** [comment]
It's correct. The `n__` function requires three arguments: the singular text, the plural and the number to evaluate. The remaining arguments are used in sprintf so, if you want to use the same number in the sprintf, you have to provide it two times. This prevent conflict with the two functionalities of the function: evaluate the singular/plural and compose the text with the values.

> Why the plural purpose is used while the value is not plural ?

Not sure what do you mean. In many languages `0` is plural (it's "0 comments", not "0 comment"). Other languages have more than one plural. You need to configure the language to get the appropiate plural evaluation.

**Comment by mlocati** [comment]
Plurals are a big subject... Many languages have two plural forms (but zero is considered sometimes as singular - eg in French - and sometimes as plural - eg in English).
Furthermore, some language doesn't have any plural form (eg. Japanese), and others have up to 6 plural forms (eg Arabic).
For a full list of rules see for instance http://mlocati.github.io/cldr-to-gettext-plural-rules/ (table built starting from CLDR data).
