### ISSUE TITLE
VueJS: Parsing HTML attributes [help wanted]

### ISSUE THREAD

**Issue by nabab** [oscarotero/Gettext#172]
We have VueJS elements and an underscore function is used for translations in the attributes of the HTML elements.

Eg: `<div :title="_('My title in English')" v-text="_('My text in English')"></div>`

Is it possible to use one of the existing extractors to parse such file? If not, once I have parsed the content with my own function, is there a way to integrate the result in a Gettext\Translations object?

Many thanks, and great work!

**Comment by oscarotero** [comment]
Hi.
Currently, there's no extractors for this. If you parse the content with your functions, you can insert these new translations easily:

```php
$translations->insert($context, $original, $plural = '');
```

For example:

```php
$translations->insert('vue-translations', 'My title in English');
$translations->insert('vue-translations', 'My text in English');
//etc...
```

**Comment by nabab** [comment]
Thanks a lot, I'll try that
