### ISSUE TITLE
Doesn't handle disabled translations well

### ISSUE THREAD

**Issue by Ugoku** [oscarotero/Gettext#173]
With this code:

```
<?php
require_once '../vendor/autoload.php';
use Gettext\Translations;

$translationsExisting = Translations::fromPoFile('sample.po');
$translationsExisting->toPoFile('sample.po');
```

I would expect my .po file to remain untouched. However, with this PO file:

```
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2018-02-08 16:10+0100\n"
"PO-Revision-Date: 2018-02-08 16:10+0100\n"
"Language: en\n"

msgid "foo"
msgstr "bar"

#~ msgid "id1"
#~ msgstr "val1"

#~ msgid "id2"
#~ msgstr "val2"

#~ msgid "id3"
#~ msgstr "val3"
```

The resulting file is this:

```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2018-02-08 16:10+0100\n"
"PO-Revision-Date: 2018-02-08 16:10+0100\n"
"Language: en\n"
": msgid "id1"msgstr "val1"msgid "id2"msgstr "val2"msgid "id3"msgstr "val3"\n"

msgid "foo"
msgstr "bar"
```

Which is an invalid file, unfortunately, and doesn't contain the disabled translations in a proper format anymore.

**Comment by oscarotero** [comment]
Hello.
I've never seen this syntax in a po file. Is it standard in the po format?
In the gettext docs I didn't find anything related with disable translations: https://www.gnu.org/software/gettext/manual/gettext.html#PO-Files

**Comment by Ugoku** [comment]
In the page you linked, see section 9.8.3, it talks about "obsolete #~ messages" :)

POEdit uses them when a translation is no longer needed (obsolete).

Use case:
- you have a certain translated text in your PO file (i.e. "latest update" -> "última actualización")
- something changes so the text ("latest update") is no longer needed. POEdit prefixes the text with `#~`
- something changes again and the text is re-introduced to the PO file. Since it's still in the file, it does not need re-translating, the translation still exists.

**Comment by oscarotero** [comment]
Ok, fair enough.
As you can guess, his is not implemented yet, but hope to be included in the next version.

**Comment by oscarotero** [comment]
Hi, I've started to work in this and have a question. Can you test if it's working fine?

**Comment by oscarotero** [comment]
I use PHPCS to test the psr-2 code format compliance (https://github.com/oscarotero/Gettext/blob/master/phpcs.xml) and psr-2 doesn't say anything about spaces between concatenation.

**Comment by briedis** [comment]
Alright, I personally use phpstorm with autoformat to PSR2.

**Comment by oscarotero** [comment]
New version released.
https://github.com/oscarotero/Gettext/releases/tag/v4.5.0

**Comment by Ugoku** [comment]
Tested this today, works great! Thanks a lot!
