### ISSUE TITLE
Support for "fuzzy" translations

### ISSUE THREAD

**Issue by odan** [oscarotero/Gettext#176]
Hi!

I'm merging translations and trying to flag all new translations as "fuzzy" like poedit does:

![image](https://user-images.githubusercontent.com/781074/39068242-eea092f6-44db-11e8-9725-f36aaa7964b4.png)

![image](https://user-images.githubusercontent.com/781074/39068268-0a06df78-44dc-11e8-8baf-268ac93a8945.png)

Poedit adds `#, fuzzy` over the `msgid` to indicate the entry as unclear.

```
#: src\Classname.php:97
#, fuzzy
msgid "Yes"
msgstr ""
```

With this visual indicator you can see what's new and needs to be translated.

At the moment I use these merge settings:

```php
$fn = $this->getFunctionName('from', $target, 'File', 1);
$translations = $translations->mergeWith(Translations::$fn($target),
    Merge::TRANSLATION_OVERRIDE | Merge::HEADERS_OVERRIDE | Merge::COMMENTS_THEIRS
);
```

The questions is how can I flag **all new and untranslated** entries as "fuzzy"?

**Comment by oscarotero** [comment]
This is a flag, so you can use the following:

```php
foreach ($translations as $translation) {
    $translation->addFlag('fuzzy');
}
```

**Comment by odan** [comment]
Thanks @oscarotero It's working now :-)

![image](https://user-images.githubusercontent.com/781074/39083260-668025b2-4562-11e8-9cdd-0722c8226d07.png)

My code:

```php
$fn = $this->getFunctionName('from', $target, 'File', 1);
$newTranslations = Translations::$fn($target);
$translations = $this->addFuzzyFlags($newTranslations, $translations);
$translations = $translations->mergeWith($newTranslations,
    Merge::TRANSLATION_OVERRIDE | Merge::HEADERS_OVERRIDE | Merge::COMMENTS_THEIRS | Merge::FLAGS_THEIRS);
```
```php
protected function addFuzzyFlags(Translations $from, Translations $to)
{
    foreach ($to as $translation) {
        if (!$from->find($translation)) {
            $translation->addFlag('fuzzy');
        }
    }

    return $to;
}
```
