### ISSUE TITLE
Translations insert translation method alternative

### ISSUE THREAD

**Issue by briedis** [oscarotero/Gettext#183]
How about a simple method `inserTranslation(Translation $translation)` instead of just `->insert($original, ..)` ? I'm building the translation items a different way and currently using `->offsetSet(null, $tarnslation)`, but that does not look very pretty :)

```
 $translation = $this->dbRowToTranslation($row);
 $translations->offsetSet(null, $translation); // ugh
```

Would be nice:

```
 $translation = $this->dbRowToTranslation($row);
 $translations->insertTranslation($translation);
```

Just asking for opinion before submitting a pull request.

**Comment by oscarotero** [comment]
`offsetSet` is a method of the ArrayAccess interface, allowing to use the `$translations` instance as an array. So the "correct" way to insert translations is simply doing:

```php
$translations[] = $translation;
```

**Comment by briedis** [comment]
Alright, at one point I thought this could be allowed, but did not know that you could do that with the array access 👍
