### ISSUE TITLE
msgstr index should start by 0 for plurals

### ISSUE THREAD

**Issue by thestanislav** [oscarotero/Gettext#189]
https://github.com/oscarotero/Gettext/blob/854ff5f5aaf92d2af7080ba8fc15718b27b5c89a/src/Generators/Po.php#L67

When I edit po files with Poedit it saves msgstr values for plurals starting at 0 index
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""

Why do you start at 1 ?

**Comment by mlocati** [comment]
It starts with 0 (see https://github.com/oscarotero/Gettext/blob/854ff5f5aaf92d2af7080ba8fc15718b27b5c89a/src/Generators/Po.php#L64 )

**Comment by thestanislav** [comment]
As I examined the code I see your store first plural translation in msgid_plural. But this format can not be read by zend framework translator. I have missing data reading mo files :(
I you sure this is correct storage specification?

**Comment by thestanislav** [comment]
Here is a simple code
```php
$translations = new \Gettext\Translations();
$translations->setLanguage('ru');

$translation = new Gettext\Translation('день', 'дней', 'дня');
$translation->setPluralTranslations([
    'день',
    'дня',
    'дней'
]);
$translations[] = $translation;
\Gettext\Generators\Po::toFile($translations, 'sample.po');
```

Content of my po file 
```
msgctxt "день"
msgid "дней"
msgid_plural "дня"
msgstr[0] ""
msgstr[1] "день"
msgstr[2] "дня"
```

Translation for msgstr[0] is missing. Am I doing something wrong?

**Comment by mlocati** [comment]
You need to call `$translation->setTranslation( 'день')` and`$translation->setPluralTranslations(['дня', 'дней'])`

**Comment by thestanislav** [comment]
Oh. I see. Thank you
Excuse me for troubling.
