### ISSUE TITLE
ISO-8859-1 encoding

### ISSUE THREAD

**Issue by oscarml** [oscarotero/Gettext#190]
Hi,
I've a web app that uses ISO-8859-1 charset

I've created the translations files with **i18n-editor**, and load translations by **fromJsonDictionaryFile**

The problem is that files generated by **i18n-editor** are saved with utf8, and then mi translations are plenty of utf8 characters.

My question is, could I override **__() global function** in order to apply and utf8_decode call?
Do you think there another simplier solution?

Thanks a lot

**Comment by oscarotero** [comment]
PHP does not allow to override a function defined previously, but you can create your own `__()` functions and require them, instead using the provided by this library. Just duplicate [this file](https://github.com/oscarotero/Gettext/blob/master/src/translator_functions.php) and modify it.

Other option (better in my opinion) is create your own Translator class. Just create a class extending [the default Translator](https://github.com/oscarotero/Gettext/blob/master/src/Translator.php) overriding or extending the methods you need. This allows to use the default functions but with your own Translator class.

And other option is convert the generated files to ISO-8859-1 charset.
