### ISSUE TITLE
JSON files - Undefined index "messages"

### ISSUE THREAD

**Issue by odan** [oscarotero/Gettext#203]
I have some other json files without a "messages" element. 
This will print a lot of warnings if I parse my files:

> Undefined index "messages" in [MultidimensionalArrayTrait.php](https://github.com/oscarotero/Gettext/blob/master/src/Utils/MultidimensionalArrayTrait.php#L82) line 82.

I think a simple "empty" check would solve that issue:

```php
if (empty($messages['messages'])) {
    return;
}
```

**Comment by oscarotero** [comment]
How do you create these json files?
`messages` should exist always.

**Comment by odan** [comment]
These are JSON files that must not be analyzed, because  I have to use the [datatables.net](https://datatables.net) component-specific translation files. Example: https://cdn.datatables.net/plug-ins/1.10.19/i18n/English.json

**Comment by oscarotero** [comment]
For plain json files, use the JsonDictionary extractor.

**Comment by odan** [comment]
Well, that's not what I'm trying to achieve. I don't want to find messages in this JSON files. The content of this files is **static** and only necessary for for the datatables.net component.

**Comment by oscarotero** [comment]
Sorry but now I'm confused. What do you need?

**Comment by odan** [comment]
I have Json files that are not intended for translation. The file extension is `.json`, but these files should be ignored if the content is not valid for the translation parser.  I found a workaround for this issue. Thank you for your attention.
