### ISSUE TITLE
load multiple domains ?

### ISSUE THREAD

**Issue by quasiperfect** [oscarotero/Gettext#217]
hi

i have tried something like this and no luck
```
$locale = 'de_DE';
$translator = new GettextTranslator();
$translator->setLanguage($locale);

$translator->loadDomain($locale, './');
$translator->loadDomain($locale, './vendor/path/');
$translator->register();
```
any suggestions ?

**Comment by oscarotero** [comment]
You are loading the same domain twice. Note also that the domain is not the same than the language (de_DE). The directory of your domain should contain a subdirectory with the locale a sub-subdirectory with the category and then the .mo file with the same name that your domain name.
For example:

```php
$locale = 'de_DE';
$domain = 'messages';

$translator = new GettextTranslator();
$translator->setLanguage($locale);

$translator->loadDomain($domain, __DIR__'/Locale');
//Loads the file Locale/de_DE/LC_MESSAGES/messages.mo
```

See [PHP gettext docs](https://www.php.net/manual/en/book.gettext.php) for more info.

**Comment by quasiperfect** [comment]
thanks @oscarotero
