### ISSUE TITLE
plural functions throw exception when translations not loaded

### ISSUE THREAD

**Issue by Gator92** [oscarotero/Gettext#35]
The plural functions, such as ngettext, in the Translator class throw an exception when translations are not loaded. On line 247, instead of throwing an exception, it should probably just fallback on the default behavior, ie:
```php
if (!isset($this->plurals[$domain])) {
    $this->plurals[$domain] = array('count' => 2, 'code' => ' return ($n != 1);;');
}`

**Comment by oscarotero** [comment]
I'm agree with this. fixed
