### ISSUE TITLE
Translations mergeWith merge flags

### ISSUE THREAD

**Issue by Gator92** [oscarotero/Gettext#36]
The merge flags passed to the Translations::mergeWith function do not have any effect. This is due to the following code staring on line 214:
```php
$add = (boolean) $method & self::MERGE_ADD;
```
The intended result here is probably to cast the result of the bitwise &, however it's casting the $method param to bool, then performing the bitwise op. This basically sets the $method to self::MERGE_ADD making the other flags meaningless. The following code produces the expected results:
```php
$add = (boolean) ($method & self::MERGE_ADD);
$references = (boolean) ($method & self::MERGE_REFERENCES);
$comments = (boolean) ($method & self::MERGE_COMMENTS);
```

**Comment by oscarotero** [comment]
Thanks again. As you can see, this feature wan't tested properly. I added some basic tests but maybe more bugs can ben found.

**Comment by Gator92** [comment]
Thanks, have been merging newly scanned php files with the main translation files - so it's nice to have the refs in place. It seems to be working in practice, but I'll put together a few unit tests to be sure.

**Comment by oscarotero** [comment]
:+1:
