### ISSUE TITLE
Comments need more separation

### ISSUE THREAD

**Issue by mlocati** [oscarotero/Gettext#38]
Currently, while reading a .po file, the comments starting with
- `# ` translator-comments
- `#. ` extracted-comments
- `#, ` flag

Are all [handled as if they where translator-comments](https://github.com/oscarotero/Gettext/blob/v2.2.3/src/Extractors/Po.php#L77-L82).
There should be a way to keep them separated...

**Comment by oscarotero** [comment]
Ok, I've added some method to add/get these comments:
```php
$translation->addExtractedComment('new comment');
$translation->getExtractedComments(); //array
$translation->hasExtractedComment(); //boolean

$translation->addFlag('flag');
$translation->getFlags(); //array
$translation->hasFlags(); //boolean
```
