### ISSUE TITLE
Reference comments in po files are parsed incorrectly

### ISSUE THREAD

**Issue by mlocati** [oscarotero/Gettext#39]
We have a .po file like this:
```po
#: attributes/address/composer.php:8 attributes/address/form.php:7
msgid   "Address 1"
msgstr  ""
```
Currently the po parser do a [simple split](https://github.com/oscarotero/Gettext/blob/v2.2.3/src/Extractors/Po.php#L84-L888) with `':'`.
In this case we'd have that we have that we call `addReference` with:
- $filename == `attributes/address/composer.php`
- $line == `8 attributes/address/form.php`

Furthermore, under Windows, we may have references like this one:
`C:/Users/Me/Documents/foo.php:1`
The above split function will result in:
- $filename == `C`
- $line == `/Users/Me/Documents/foo.php`

We'd need a better reference parser...

**Comment by oscarotero** [comment]
Thank you for the feedback. I didn't know a comment can contain more than one reference.
Fixed using a regex.

**Comment by mlocati** [comment]
Great, thank you!
