### ISSUE TITLE
po strings are incorrectly read

### ISSUE THREAD

**Issue by mlocati** [oscarotero/Gettext#40]
Let's say we have a .po file like this:
```po
msgid   "Address 1"
msgstr  ""
```
When we read this .po file, we [split](https://github.com/oscarotero/Gettext/blob/v2.2.3/src/Extractors/Po.php#L71) the `'msgid   "Address 1"'` string in two:
- `'msgid'`
- `'  "Address 1"'`
Since the second line starts with a space, the [clean function](https://github.com/oscarotero/Gettext/blob/v2.2.3/src/Extractors/Po.php#L166) behaves incorrectly.

**Comment by mlocati** [comment]
PS: multiple spaces between msgid and its value occurs when xgettext gets called with the `--indent` option

**Comment by oscarotero** [comment]
Good catch!
solved in the last commit.

**Comment by mlocati** [comment]
You're very fast!
