### ISSUE TITLE
Add support of multiline translations

### ISSUE THREAD

**Issue by andreymeretsky** [oscarotero/Gettext#42]
Hi! =) 
Here https://github.com/oscarotero/Gettext/blob/master/tests/files/po.po 
you show few examples, but there is no example with multiline translation such as 
#: /var/www/test/test.php:96
msgid "{test1}"
msgstr ""
"test1\n"
"<div>\n"
"  test2\n"
"</div>\n"
"test3"

1. Why I say about that?
Not so far I added an issue that i need support of \n in my strings and you did it.
And your lib make multiline strings such as msgstr "test1\n <div>\n  test2\n </div>\n test3"
But it isn't valid for converting to mo. 
https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html (see end of this page)
Because I have multiline translation such as
msgstr "test1\n <div>\n  test2\n </div>\n test3"
wordpress cuts this translation and echo only 'test1' to browser.
Desktop program Poedit makes multiline msgstr as i show in the beginning of issue and makes a valid mo. If i try to convert it to mo with your lib it cuts only to 'test1' >:(

Help to solve this problem. Please tell me if I wrong =) 

P.s. This editor broke my text) Here is screen of original
http://picsee.net/upload/2015-01-16/1d3b04ab37aa.png

**Comment by oscarotero** [comment]
Hi
I've implemented two new tests with multiline translations:
https://github.com/oscarotero/Gettext/blob/master/tests/files/po.po#L59-L70
and the Po parser has the same result:
https://github.com/oscarotero/Gettext/blob/master/tests/PoExtractorTest.php#L92

so I guess this is a problem with the mo generator, that replaces all linebreaks by `\x00` (https://github.com/oscarotero/Gettext/blob/master/src/Generators/Mo.php#L40). I don't know how to solve this, because I do not use mo files at all.

**Comment by mlocati** [comment]
Why does the mo generator replaces linebreaks by \x00?

**Comment by oscarotero** [comment]
The mo converter code has been adapted from the Joss Crowcroft implementation (https://github.com/phpmo/php.mo/blob/master/php-mo.php#L179) that uses this character to join the msgid, msgid_plural and msgstr.

**Comment by mlocati** [comment]
I think that that original implementation concatenates with \0 the different plural strings. It does not touch the single strings

**Comment by mlocati** [comment]
To check a generated .mo file you can use the command line tool `msgunfmt` that takes a mo files and decompiles it to a po file. 
For unix it's part of the gettext tools package. For Windows you can use [my binaries](http://mlocati.github.io/gettext-iconv-windows/)

**Comment by mlocati** [comment]
This issue should have been fixed.

**Comment by oscarotero** [comment]
I guess so.
