### ISSUE TITLE
Headers handling

### ISSUE THREAD

**Issue by mlocati** [oscarotero/Gettext#55]
IMHO we should remove the $context and $language variables from the `Translations` class.
They should always be included only in the $headers variable.
If we do so, we can simplify the extractors.
For instance, we could remove these lines: https://github.com/oscarotero/Gettext/blob/c701efc6f88385471ad7d6f34ad11c5301cc01f5/src/Extractors/Po.php#L41-L48
Furthermore, if we do so, we prevent strange situations where we have a $language set to something and $header['Language'] set to something else.

What do you think?

**Comment by oscarotero** [comment]
Sounds good. Simpler is better :+1:
