### ISSUE TITLE
Wrong iteration over lines?

### ISSUE THREAD

**Issue by 19Gerhard85** [oscarotero/Gettext#65]
Hey Oscar,

thanks for the awesome class! I'm using it to parse .po files (without headers). During developement I encountered a problem with the class: the first translation isn't parsed. I tracked down this line as the source of the problem:

```php
for ($n = count($lines); $i < $n; $i++) {
```
https://github.com/oscarotero/Gettext/blob/master/src/Extractors/Po.php#L42

Why are you iterating over the lines like this?

I suggest to replace this line with

```php
for ($i = 0; $i <= count($lines); $i++) {
```
or
```php
foreach ($lines as $i => $line) {
```

If you like I can provide you a pull request.

Greets

**Comment by oscarotero** [comment]
Hi.
This code is right, because `$n` is the total number of lines available and `$i` is the current line number (that it's created in the begining and used also to parse the headers). Can I see the po file you want to parse? Maybe the problem is the abscense of headers.

**Comment by 19Gerhard85** [comment]
Hi Oscar,

thanks for your fast reply.

Here is my po file: http://we.tl/1EUyj3funE

Greets

**Comment by oscarotero** [comment]
Hello @19Gerhard85 
I've pushed new changes to fix this problem. The Po extractor was created to always expect some headers at first. I've fixed this, so now it is non mandatory. Can you check it before launch a new release, please?

**Comment by 19Gerhard85** [comment]
Hi @oscarotero the fix works like a charm. Thanks!
