### ISSUE TITLE
Plural rules definition

### ISSUE THREAD

**Issue by mlocati** [oscarotero/Gettext#67]
@oscarotero Could you wait a few days before publishing a new release?
IMHO some of the plural rules that we took from http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html are not correct.
I discovered [two discrepancies](https://github.com/translate/l10n-guide/issues?q=is%3Aissue+author%3Amlocati) but it seems that nobody is taking care of them, so IMHO that repository is not well maintained.
I'm going to write a script that takes the rules from [CLDR](http://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules) and converts them to [gettext](http://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html).
It's not that easy, since CLDR rules refer to decimals and negative numbers, whereas gettext works with unsigned integers, but I'm working on it.

**Comment by oscarotero** [comment]
That's great. No problem, I can wait.

**Comment by mlocati** [comment]
Done. See https://github.com/mlocati/cldr-to-gettext-plural-rules/

**Comment by oscarotero** [comment]
Nice!
I think this data should be saved in an external php file, so it can be re-generated in any time without modify the Locales class. What do you think about implementing something like this?:
```
php convert.php phparray locales-data.php
```
So, in Locales class, we can create a method to retrieve this information:
```php
public static function getData()
{
    if (!isset(self::$data)) {
        self::$data = include __DIR__.'/locales-data.php';
    }

    return self::$data;
}

**Comment by mlocati** [comment]
Nice idea. Done :wink:

**Comment by oscarotero** [comment]
Ok, I've changed the Locales class to work with the new source. There are some changes, for example in the russian language that now has 4 plurals instead 3, I hope this is right (I have no idea).
I don't know whether the territories data is useful, but I've keept it anyway.

**Comment by mlocati** [comment]
> The russian language that now has 4 plurals instead 3, I hope this is right (I have no idea)

Previously we had 3 plurals with this formula:
`(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)`

But the CLDR data says this:
```
"ru": {
    "pluralRule-count-one": "v = 0 and i % 10 = 1 and i % 100 != 11 @integer 1, 21, 31, 41, 51, 61, 71, 81, 101, 1001, …",
    "pluralRule-count-few": "v = 0 and i % 10 = 2..4 and i % 100 != 12..14 @integer 2~4, 22~24, 32~34, 42~44, 52~54, 62, 102, 1002, …",
    "pluralRule-count-many": "v = 0 and i % 10 = 0 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 11..14 @integer 0, 5~19, 100, 1000, 10000, 100000, 1000000, …",
    "pluralRule-count-other": "   @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …"
},
```
As you can see, there should be 4 plurals.
And the new formula is
```
(n % 10 == 1 && n % 100 != 11) ? 0
:
((n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) ? 1
:
((n % 10 == 0 || n % 10 >= 5 && n % 10 <= 9 || n % 100 >= 11 && n % 100 <= 14) ?
2
:
3
))
```
Which seems congruent with the CLDR data (for gettext we have that `n == i` and `v == 0`)

BUT the fourth case never occurs for integers... So, yes: it seems there's still some optimizations to be done...

**Comment by mlocati** [comment]
[There are 4 cases](https://travis-ci.org/mlocati/cldr-to-gettext-plural-rules/jobs/50257428) that I have to investigate.

You have eagle eyes ;) Thanks!

**Comment by mlocati** [comment]
@oscarotero Ok, I added a procedure that removes the superfluous cases; the languages cleaned have been the 4 problematic ones: be` - Belarusian, `pl` - Polish, `ru` - Russian and `uk` - Ukrainian.

**Comment by mlocati** [comment]
Just a side note: Daiki Ueno (head developer of the gettext tools) seems  [interested](http://lists.gnu.org/archive/html/bug-gettext/2015-02/msg00016.html) in my [cldr-to-gettext-plural-rules](https://github.com/mlocati/cldr-to-gettext-plural-rules/) :wink:

**Comment by oscarotero** [comment]
That's fantastic!!
I've pushed some changes with the new data exported by your tool and everything works fine.

> You have eagle eyes ;) Thanks!

The phpunit test has eagle eyes :eyeglasses:

**Comment by mlocati** [comment]
@oscarotero Just a notice: https://packagist.org/packages/gettext/languages

**Comment by oscarotero** [comment]
Ok.
Do you think it's better to include this package as a dependency and generate the data using the composer post-install event?

**Comment by mlocati** [comment]
If you include my package, you can also use the Language class without using pre-generated php code...
