### ISSUE TITLE
Strings quoting

### ISSUE THREAD

**Issue by vkardash** [oscarotero/Gettext#68]
Hi oscarotero,

first of all thank you for great package. You've done great work :)

in class "Gettext\Generators\Po" you have "quote" method. In case of having tabs in original or translation string, method will not convert it to \t but editors do (same for "Gettext\Extractors\Po" ->clean).

Could you please add "\t" handling to this methods, or at least make "quote" and "clean" protected instead of private, so programmer can change this methods behavior.

Thank you.

**Comment by oscarotero** [comment]
Hi, @vkardash 
Yes, you're right. I'll made this change. Thank you for the feedback.

**Comment by vkardash** [comment]
Also same about "\" .. if left it unescaped POEdit can't validate the string. 
I've temporary made such changes:
return '"'.str_replace(array("\r", "\n", "\t", '\\', '"'), array('', '\n', '\t', '\\\\', '\\"'), $string).'"';
Think it's not full list of changes .. but close :)

**Comment by vkardash** [comment]
And possible it will be Ok to change "Gettext\Generators\Po" method "toString" this part:
$lines[] = 'msgstr '.self::quote($translation->getTranslation());
with multiline realization (same as for $msgid) ?

**Comment by oscarotero** [comment]
Fixed this. It will be available on the next release (3.2)
