### ISSUE TITLE
Updating to 97b3d05 I get a unnecessary PHP version suggestion.

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/Gettext#70]
I have updated from 23795c3 to 97b3d05 and I get this suggestion:

`gettext/languages suggests installing php>=5.4 (In order to export with prettyjson you need at least PHP 5.4+)`

But I'm using PHP 5.5.9-1ubuntu4.5

**Comment by oscarotero** [comment]
This is a suggestion of [gettext/languages](https://github.com/mlocati/cldr-to-gettext-plural-rules) dependency created by @mlocati 
It should be great if composer checked whether the suggested packages were already installed before display the message, but this is a composer issue.

**Comment by mlocati** [comment]
That ugly message won't be displayed anymore. I just released [gettext/languages v2.1](https://github.com/mlocati/cldr-to-gettext-plural-rules/releases/tag/2.1.0).

**Comment by oscarotero** [comment]
:+1:
