### ISSUE TITLE
Translations::fromPoFile not in source code

### ISSUE THREAD

**Issue by mbaush77** [oscarotero/Gettext#75]
The README gives a few examples on how to use the library, but I could not find the method "Translations::fromPoFile". I installed the library through composer (gettext/gettext) v3.4.2.

Thanks!

**Comment by mlocati** [comment]
It's handled by https://github.com/oscarotero/Gettext/blob/master/src/Translations.php#L54

**Comment by mbaush77** [comment]
Ah got it! My IDE did not handle these kind of dynamic methods. Thanks

**Comment by oscarotero** [comment]
:+1:
