### ISSUE TITLE
Problem with translating plural forms

### ISSUE THREAD

**Issue by zaksmok** [oscarotero/Gettext#76]
Hello. I've got .po file created with poEdit with translated plural form (http://pastebin.com/6YvDx6gY).

Using translation function "echo __('dragon');" works fine but plural translations like "echo n__('%s apple', '%s apples', 1);" or "echo n__('%s apple', '%s apples', 2);" gives "%s jabłko" and "%s jabłek".

So translation is good but dynamic value %s is not set,

I cannot figure out what I'm doing wrong. Can you help me?

**Comment by mlocati** [comment]
Try with `n__('%s apple', '%s apples', 2, 2);`: does it work?

**Comment by zaksmok** [comment]
yes it works. But why i have to double $value?

**Comment by mlocati** [comment]
`n__('%s apple', '%s apples', 2)` give you the correct plural translated string for 2 apples.
Further arguments (after the third), if specified, are used in a sprintf function to put these values to the translated string.

**Comment by zaksmok** [comment]
i see, thank you for response. Have a great day!

**Comment by Vlasterx** [comment]
Hello,
sorry for necromancy and resurrection of this old question, but I have a follow up question:

Here is the PO file

```
msgid "LNG_CODE"
msgstr[0] "I wrote %s line of code"
msgstr[1] "I wrote %s lines of code"
```

and this is the PHP translation

`echo n__('LNG_CODE', 'LNG_CODE', 101, 101);`

which outputs

`I wrote 101 lines of code`

Is there a more logical way to solve this without repeating the code several times?
