### ISSUE TITLE
merge override

### ISSUE THREAD

**Issue by jonhargett** [oscarotero/Gettext#80]
Would it be possible to add a merge option to use translations in translation2 to override the translations in translation1?
For instance, if you have 2 po files:
```
# default.po
msgid "unit"
msgstr "Unit"

# override.po
msgid "unit"
msgstr "Use this instead"

$translations = gt\Translations::fromPoFile($path . '/' . $lang . '/LC_MESSAGES/default.po');
$domainTranslation = gt\Translations::fromPoFile($path . '/' . $lang . '/LC_MESSAGES/override.po');
$translations->mergeWith($domainTranslation, gt\Translations::MERGE_OVERRIDE);
```
The idea here is that within each language, there would be a default translation and then another translation file that could override _some_ of the msg strings.

**Comment by oscarotero** [comment]
Good point. I added this constant and am going to release a new version.
Thanks

**Comment by jonhargett** [comment]
This works great! Thank you very much for your quick response.
