### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by lineldcosta** [oscarotero/Gettext#83]
Hi, 
Is there way to remove the tokens from the existing PO file.

Thanks,
Lionel

**Comment by oscarotero** [comment]
`Gettext\Translations` extends `ArrayObject` so you can use the array syntax to manipulate the content (adding or remove translations). For example:
```php
$translations = Gettext\Translations::fromPoFile('my-translations.po');
$translation = $translations->find('context', 'original');

//we need the id
$id = $translation->getId();

//the id is used as key
assert($translations[$id] === $translation);

//so, we can remove this entry
unset($translations[$id]);

//and generate the .po again
$translations->toPoFile('my-translations.po');
```

**Comment by lineldcosta** [comment]
Yeah tats working..  Thanks..

**Comment by vielhuber** [comment]
This is outdated. Use

```$translations->remove($translation)```

instead.
