### ISSUE TITLE
Undefined dgettext() Method

### ISSUE THREAD

**Issue by parkerj** [oscarotero/Gettext#86]
When using function d__($domain, $original), I get the following error message:

```
[11-Nov-2015 00:11:16 America/New_York] PHP Fatal error:  Call to undefined method Gettext\BaseTranslator::dgettext() in /Applications/AMPPS/www/et/libs/gettext/src/translator_functions.php on line 78
```
Line 78 is:

`$text = BaseTranslator::dgettext($domain, $original);`

**Comment by oscarotero** [comment]
Ooops. This is a bug. Solved in the new version 3.5.5.

**Comment by parkerj** [comment]
Thanks.

**Comment by parkerj** [comment]
This may need to be re-opened because I am not sure if this is working even after implementing your changes. Below is my example code:

```php
include_once "gettext/src/autoloader.php";
include_once "cldr-to-gettext-plural-rules/src/autoloader.php";

$t = new Gettext\Translator();
$translations = Gettext\Translations::fromPoFile('/Applications/AMPPS/www/et/app/lang/edutrac-sis-it_IT.po');
$t->loadTranslations($translations);
//$t->register();

echo $t->gettext('Screens');

echo '<br />';

//echo d__('edutrac-sis', 'Screens');

echo $t->dgettext('edutrac-sis', 'Screens');

echo '<br />';

echo $t->dpgettext('edutrac-sis', null, 'Screens');
```
And the output is:

```
Gestione
Screens
Screens
```
As you can see, the first one is translated, but the last two are not. Also, it doesn't translate when I use the d__() function. It returns the original string.

**Comment by oscarotero** [comment]
The domain of the .po file is defined within the `X-Domain` header. For example: https://github.com/oscarotero/Gettext/blob/master/tests/files/po.po#L15
Make sure your .po file has the correct domain.

**Comment by parkerj** [comment]
Ah, got it. Thanks.
